version: '3.7'

services:
  api:
    container_name: api
    image: api:latest
    build:
      context: backend/
      dockerfile: Dockerfile
    ports:
      - 8087:8080
  app:
    container_name: app
    image: app:latest
    build:
      context: frontend/
      dockerfile: Dockerfile
    ports:
      - 8088:80