#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname $0)/.."

export BUILD_NUMBER=${BUILD_NUMBER:-latest}

echo "Generating Executable JAR"

mvn clean package -Dmaven.test.skip=true

echo "Building Docker image"
docker build -t api:${BUILD_NUMBER} .

