#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname $0)/../backend"

echo "Generating Executable JAR"

mvn clean package -Dmaven.test.skip=true

cd ..

echo "Building Docker image"
docker-compose up --build